#!/bin/bash
export SCRIPTPATH="$(dirname "$(readlink -f "$0")")"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down
chmod +x /tmp/leftwm-theme-down

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --config $HOME/.config/leftwm/themes/current/picom.conf &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton --config $HOME/.config/leftwm/themes/current/compton.conf &> /dev/null &
fi

# Set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill "$SCRIPTPATH"/background.jpg
fi

index=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="main"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar/config.ini -q $barname &> /dev/null &
  let index=index+1
done
